yast/yast-security

package/yast2-security.changes, src/include/security/dialogs.rb, src/modules/Security.rb, test/SCRStub.rb, test/data/system/etc/login.defs, test/data/system/etc/sysconfig/clock, test/data/system/etc/sysconfig/cron, test/data/system/etc/sysconfig/displaymanager, test/data/system/etc/sysconfig/locate, test/data/system/etc/sysconfig/mail, test/data/system/etc/sysconfig/security, test/data/system/etc/sysconfig/services, test/data/system/etc/sysctl.conf, test/security_test.rb, testsuite/tests/Level1.out, testsuite/tests/Level2.out, testsuite/tests/Level3.out, testsuite/tests/Write.out
Some cleanup and tests needed in order to be able to work on bnc#907907 with confidence.
Sorry for not separating in commits the zombie killing from the spliting into smaller methods, but the latter is very simple (just moving the code a little bit).
https://bugzilla.suse.com/show_bug.cgi?id=907907
=> Code cleanup and some fixes

package/yast2-security.changes, package/yast2-security.spec, src/data/security/services.yml
I found this while looking into https://bugzilla.suse.com/show_bug.cgi?id=941620 (the yast2-security backport). I need it merged in order to have a smooth backport.
=> Added new optional services (bnc#942379)

package/yast2-security.changes
I got this mail from the maintenance team:
> Maintenance identified that some fixes planned for the next update of this package are not referenced in the change log of the package that was accepted into SUSE:SLE-12-SP2:GA.
> We would like to ask your help to verify if these bugs are fixed or not in SLE 12-SP2. In case they are not, please submit the fixes as soon as possible to SUSE:SLE-12-SP2:GA. If they are already fixed
(perhaps the package was updated to a new major version which is no longer affected by the bug), we would appreciate if you could still add a reference to the package's change log.
> If there's no known fix for this bug yet or our data is incorrect, please reply to this mail to let us know.
> Here is the bug https://bugzilla.suse.com/buglist.cgi?bug_id=941620
Since the …
=> Add more info to changelog to help tracking

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb, test/security_test.rb
Adapts sysctl handling to use the new [Yast2::CFA::Sysctl](https://github.com/yast/yast-yast2/pull/966) class so the configuration is written to a YaST specific file under `/etc/sysctl.d`.
=> Write sysctl settings to /etc/sysctl.d

package/yast2-security.changes, package/yast2-security.spec, src/clients/security.rb, src/clients/security_auto.rb, src/modules/Security.rb
After moving the `/etc/login.defs` to `/usr/etc/login.defs`, YaST2 security does not find the current configuration. The problem is that the fallback encryption method is `des`, which causes users/groups passwords to use that method instead of `sha512`.
See https://bugzilla.suse.com/show_bug.cgi?id=1157541
Use `sha512` as default. In the screenshot below you can see the `/etc/shadow` content and the security settings screen after applying the patch.
=> Change default encrypt method

package/yast2-security.changes, package/yast2-security.spec, src/autoyast-rnc/security.rnc
Added to rnc file: sys_gid_max, sys_gid_min, sys_uid_max,
sys_uid_min, hibernate_system, kernel.sysrq, mandatory_services,
net.ipv4.ip_forward, net.ipv4.tcp_syncookies, net.ipv6.conf.all.forwarding (bsc#1158301).
=> updated rnc file

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb
https://bugzilla.suse.com/show_bug.cgi?id=1160890
https://trello.com/c/3Y9HSV8m
`/bin/systemctl` symlink is gone.
Don't use it.
=> don't use /bin/systemctl compat symlink (bsc#1160890)

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb, test/levels_test.rb, test/security_test.rb
This module manage some YaST sysctl config file attributes. But, after modifying the settings it does not apply the network changes to the running system. 
In the past that responsibility was handle by `boot.ipconfig` but it is not the case anymore once we moved to systemd. 
Currently, if there is at least a conflict with other sysctl config files, the error is reported but the changes are not written as you can check in the code:
https://github.com/yast/yast-security/blob/master/src/modules/Security.rb#L594
https://github.com/yast/yast-yast2/pull/1021/files#diff-4216cbac8e98ed10343a00513e10e917R128
Thus, the changes done in the UI are lost, and need to be modified manually later.
- https://trello.com/c/MoWIKnDK/1754-3-sles15-sp2-p2-1167234-ipforwarding-in-yast2-security-sets-new-value-onl …
=> Apply sysctl changes (bsc#1167234)

.rubocop.yml, Rakefile, package/yast2-security.changes, package/yast2-security.spec, src/autoyast-rnc/security.rnc, src/clients/security.rb, src/data/security/level1.yml, src/data/security/level2.yml, src/data/security/level3.yml, src/include/security/dialogs.rb, src/include/security/helps.rb, src/include/security/levels.rb, src/include/security/widgets.rb, src/lib/security/ctrl_alt_del_config.rb, src/lib/security/display_manager.rb, src/modules/Security.rb, test/levels_test.rb, test/security_test.rb
The PR makes YaST select between pam_pwquality and pam_cracklib depending on availability.
For https://trello.com/c/ahoBngck/1948-5-ostumbleweed-p5-1171318-build-20200506-yast-security-module-integrate-with-pampwdquality and https://bugzilla.suse.com/show_bug.cgi?id=1171318. Also fixes https://bugzilla.suse.com/show_bug.cgi?id=1174619.
=> Use pam_pwquality instead of pam_cracklib depending on availability

.rubocop.yml, package/yast2-security.changes, package/yast2-security.spec, test/security_test.rb
- Added a missing mock, do not query the installed PAM modules in the testing system
=> Fixed randomly failing unit tests

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1174619
- https://trello.com/c/AppUwK8q
Pass `--cracklib-dictpath` option to PAM in the correct way.
This has been fixed in `master` branch as part of https://github.com/yast/yast-security/pull/70.
=> set cracklib dictpath correctly (bsc#1174619)

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb, test/security_test.rb
AY-Import: Translate <enable_sysrq> setting to <kernel.sysrq> with the correct value format (bsc#1177720).
=> Translate <enable_sysrq> to <kernel.sysrq> with the correct value

.rubocop.yml, package/yast2-security.changes, package/yast2-security.spec, src/include/security/dialogs.rb, src/include/security/widgets.rb, src/lib/security/display_manager.rb, test/security_test.rb
Removed obsolete setting DISPLAYMANAGER_SHUTDOWN from /etc/sysconfig/displaymanager (bsc#1175495).
=> Removed obsolete setting DISPLAYMANAGER_SHUTDOWN

package/yast2-security.spec
`Y2Security::SelinuxConfig` added in #83  makes use of Yast::Bootloader.
=> Update spec files with new requirement

package/yast2-security.changes, package/yast2-security.spec, src/lib/cfa/selinux.rb, src/lib/y2security/selinux.rb, test/cfa/selinux_test.rb, test/data/system/etc/selinux/config, test/y2security/selinux_test.rb
Related to [1] and [2], this PR introduces changes and improvements in the former `Y2Security::SelinuxConfig` class added in #83 and now renamed to `Y2Security::Selinux`. As consequence of its improvements, a new `CFA::Selinux` class has been added to handle the SELinux configuration file `/etc/selinux/config` (only able to read and write the `SELINUX` value by now)
Some of the changes that worth to mention are
* The _#mode_ proposal has become _lazy_, instead of triggering it in the constructor (agreed after working on https://github.com/yast/yast-firewall/pull/144, where too much mock had to be used to fix the test suite, which was a kind of symptom that the proposal was _miss-placed_)
* Improved the _#mode_ loading/detection, which is not as easy as it looks at glimpse because of …
=> Refactor Y2Security::SelinuxConfig (now Y2Security::Selinux)

package/yast2-security.changes, package/yast2-security.spec, src/autoyast-rnc/security.rnc, src/clients/security_auto.rb, src/lib/y2security/selinux.rb, src/modules/Security.rb, test/levels_test.rb, test/security_test.rb
Related to https://github.com/yast/yast-security/pull/83, this PR adds support for SELinux in AutoYaST.
---
<sub>Replaces #85 after _updating_ it to make use of recent changes introduced in yast/yast-security#87</sub>
=> AutoYaST for SELinux

Dockerfile, Rakefile, package/yast2-security.changes, package/yast2-security.spec, src/clients/security_auto.rb, src/lib/cfa/selinux.rb, src/lib/y2security/selinux.rb, src/modules/Security.rb, test/cfa/selinux_test.rb, test/security_test.rb, test/y2security/selinux_test.rb
In summary, it adds the SELinux support (also in AutoYaST).
Part of https://trello.com/c/g94xQBDM/ (internal link) and related to work mainly done in https://github.com/yast/yast-security/pull/83, https://github.com/yast/yast-security/pull/87, and https://github.com/yast/yast-security/pull/88.
---
Changes picked from SLE-15-SP2 branch following the [YaST Maintenance work flow](https://yastgithubio.readthedocs.io/en/latest/maintenance-branches/#maintenance-work-flow).
=> [master] Add SELinux support

package/yast2-security.changes, package/yast2-security.spec, src/lib/y2security/selinux.rb, test/y2security/selinux_test.rb
As part of https://jira.suse.com/browse/SLE-17307 Epic (internal  link), the `.autorelabel` file should be moved from `/` to `/etc/selinux/` when the root filesystem will be mounted as read-only.
<details>
<summary>Show/hide an excerpt of requirement description</summary>
> [...]
> 
> 6. If a read-only root filesystem is used:
>      /.autorelabel needs to be deleted
>      /etc/selinux/.autorelabel needs to be touched
> 
</details>
---
* Added unit tests
* Tested manually in a SLE-15-SP2
<details>
<summary>Show/hide screenshot</summary>
---
</details>
---
Related to #87
=> [SLE-15-SP2] Move SELinux .autorelabel file

package/yast2-security.changes, package/yast2-security.spec, src/lib/y2security/selinux.rb, test/y2security/selinux_test.rb
This PR sync `master` branch with `SLE-15-SP2` after introducing changes to move the _.autorelabel_ SELinux file from `/` to `/etc/selinux/` when the root fs will be mounted as read-only.
See https://github.com/yast/yast-security/pull/94
---
Related to #87
=> [master] Move SELinux .autorelabel file

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb
Change the `SELinux` resolvable unique id used in auto-installation to be consistent with the one used by normal installation.
See https://github.com/yast/yast-firewall/blob/4c1d0ef2db1f982959124186dbd374d722369773/src/lib/y2firewall/clients/proposal.rb#L229-L230
---
Related to https://github.com/yast/yast-security/pull/88 and https://github.com/yast/yast-firewall/pull/144
=> Change the unique id for SELinux resolvable

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb
Change the `SELinux` resolvable unique id used in auto-installation to be consistent with the one used by normal installation.
https://github.com/yast/yast-installation/blob/7c19909e9700242209645cf12a4daffe1cd54194/src/lib/installation/clients/security_proposal.rb#L244-L247
---
Related to https://github.com/yast/yast-security/pull/88 and https://github.com/yast/yast-installation/pull/920
=>  Change the unique id for SELinux resolvable

package/yast2-security.changes, package/yast2-security.spec, src/lib/y2security/selinux.rb, test/y2security/selinux_test.rb
Related to https://bugzilla.suse.com/show_bug.cgi?id=1182894, `Y2Security::Selinux` stop writing the bootloader in insts-sys by making use of `Yast::Stage.initial` instead of `Yast::Mode.installation`.
---
Originally sent by @jreidinger at https://github.com/yast/yast-security/pull/98 as part of https://github.com/yast/yast-installation/pull/923 and slightly related to https://github.com/yast/yast-security/pull/87
=> [SLE-15-SP2] Y2Security::Selinux does not write bootloader in insts-sys

package/yast2-security.changes, package/yast2-security.spec, src/lib/y2security/selinux.rb, test/y2security/selinux_test.rb
Related to https://bugzilla.suse.com/show_bug.cgi?id=1182894, `Y2Security::Selinux` stop writing the bootloader in insts-sys by making use of `Yast::Stage.initial` instead of `Yast::Mode.installation`.
---
Originally sent by @jreidinger at https://github.com/yast/yast-security/pull/98 as part of https://github.com/yast/yast-installation/pull/923 and slightly related to https://github.com/yast/yast-security/pull/87
=> Y2Security::Selinux does not write bootloader in insts-sys

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb
Linked to https://github.com/yast/yast-autoinstallation/pull/736, helps to solve the issue reported at https://bugzilla.suse.com/show_bug.cgi?id=1182543 ensuring that defined SELinux patterns are set when needed, no matter if imported security settings results in an empty collection.
Tested manually via `yupdate` using `SUSE-MicroOS-5.0-DVD-x86_64-Build85.5` and also applying changes proposed at https://github.com/yast/yast-autoinstallation/pull/736
=> [SLE-15-SP2] Fix Security#Import ensuring SELinux patterns are set

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb
Almost the same than #101 (this does not need changes in `yast-autoinstallation`), but for `master` branch.
It helps to avoid issues similar to https://bugzilla.suse.com/show_bug.cgi?id=1182543, ensuring that defined SELinux patterns are set when needed, no matter if imported security settings results in an empty collection.
=> Fix Security#Import ensuring SELinux patterns are set

package/yast2-security.changes
Fixes wrong (and now duplicatd) `4.2.21` version number in the changelog introduced in #101
=> [SLE-15-SP2] Fix duplicated version number in changelog

package/yast2-security.changes, package/yast2-security.spec, src/lib/y2security/selinux.rb, test/y2security/selinux_test.rb
Fix https://bugzilla.suse.com/show_bug.cgi?id=1182940 by making SELinux not configurable when running on [**W**indows **S**ubsystem for **L**inux](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux). Thus, not calling to `Yast::Bootloader` for reading/writing boot kernel params.
> Since SELinux has to be configured via boot kernel params, it makes no
> sense to offer such feature when running on Windows Subsystem for
> Linux[1] becuase the system will be **booted via Windows, so Linux
> bootloader is useless here**[2].
> 
> [1] https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux
> [2] https://yastgithubio.readthedocs.io/en/latest/WSL/
=> [SLE-15-SP2] Make SELinux not configurable when running on WSL

package/yast2-security.changes, package/yast2-security.spec, src/lib/y2security/selinux.rb, test/y2security/selinux_test.rb
Fix https://bugzilla.suse.com/show_bug.cgi?id=1182940 by making SELinux not configurable when running on [**W**indows **S**ubsystem for **L**inux](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) since it makes not sense considering that [WSL does not have/use a Linux kernel](https://github.com/yast/yast-security/pull/104#issuecomment-789896900).
---
The same than #104, but for `master` branch.
Trello card (internal link): https://trello.com/c/g5u0hw0j
=> Make SELinux not configurable when running on WSL

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb, test/levels_test.rb, test/security_test.rb
YaST Firstboot is crashing when running in Windows Subsystem for Linux (WSL) because a `Y2Security::Selinux#mode` calls that triggers a `Bootloader#Read`
See https://bugzilla.suse.com/show_bug.cgi?id=1182940
Do not `#read_selinux_settings` when SElinux [is not configurable](https://github.com/yast/yast-security/blob/9d96d6e7a8ecc27caa910cc4e5ea7260926e4b3d/src/lib/y2security/selinux.rb#L223-L234).
* Added unit tests
* Tested manually
* Download the Windows 10 image and the appx from openQA.
* [Enable WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10#manual-installation-steps)
* [Import the certificate](https://social.msdn.microsoft.com/Forums/en-US/b9281639-5bb4-4064-a5dc-c769183d7d91/new-certificate-must-be-installed-for-this-app-package)
* Install the appx.
* Launch the …
=> [SLE-15-SP2] Do not set SELinux mode when it is not configurable

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb, test/levels_test.rb, test/security_test.rb
The same than https://github.com/yast/yast-security/pull/106, but for `master` branch.
> YaST Firstboot is crashing when running in Windows Subsystem for Linux (WSL) because a `Y2Security::Selinux#mode` calls that triggers a `Bootloader#Read`
>
Related links
* https://bugzilla.suse.com/show_bug.cgi?id=1182940
* https://openqa.suse.de/tests/5673243#step/firstrun/16
For manual testing:
>   * Download the Windows 10 image and the appx from openQA.
>   * [Enable WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10#manual-installation-steps)
>   * [Import the certificate](https://social.msdn.microsoft.com/Forums/en-US/b9281639-5bb4-4064-a5dc-c769183d7d91/new-certificate-must-be-installed-for-this-app-package)
>   * Install the appx.
>   * Launch the appx takes you to a console. …
=> Do not set SELinux mode when it is not configurable

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb, test/levels_test.rb, test/security_test.rb
Adapts yast2-security to use the `CFA::LoginDefs` class instead of `CFA::ShadowConfig`. Please, find the rationale in https://github.com/yast/yast-yast2/pull/1152.
=> bsc#1184131: use /etc/login.defs for shadow configuration

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb, test/security_test.rb
The `Security` module offers a `Read` method which raises an exception if reading the settings fails (e.g., parsing error, file does not exist, etc). But that exceptions are lost when the `Security#Read` is called from a perl module like `Users.pm`. As result, the perl code has no way to check if there was an error while reading the security settings.
* Related to https://bugzilla.suse.com/show_bug.cgi?id=1177183
* Needed for https://github.com/yast/yast-users/pull/317
Add a new method `Security#SafeRead` which avoids to raise exceptions. It stores the error message when reading the settings fails.
=> Read without exceptions

package/yast2-security.changes, package/yast2-security.spec, src/lib/y2security/lsm/selinux.rb
Bring back the `selinux=1` boot parameter when SELinux is selected and it is not disabled explicitly. Related to #115
=> Pass selinux=1 boot parameter when not disabled explicitly

package/yast2-security.changes, package/yast2-security.spec, src/autoyast-rnc/security.rnc, src/lib/y2security/lsm/config.rb, src/modules/Security.rb, test/security_test.rb, test/y2security/lsm/config_test.rb
In case that the **Linux Security Module** should not be configured during the installation then we should not select any module at all in order to not write the boot parameters.
Related to #115
After discussing the current behavior with @dgdavid it probably makes sense to have also a differentiation between **selectable** and **configurable** for the **LSM** config, adding the **selectable** tag also there.
In case that LSM is not selectable then the widget and probably the proposal could be hidden but we could select a default LSM in case of configurable. If it is marked as no configurable then it will be hidden and also skipped completely.
=> Do not propose any Linux Security Module if declared as not configurable

package/yast2-security.changes, package/yast2-security.spec, src/lib/y2security/lsm/app_armor.rb, src/lib/y2security/lsm/selinux.rb, test/y2security/lsm/app_armor_test.rb, test/y2security/lsm/selinux_test.rb
As it seems that we need to specify also the **integrity** module in order to be able to use the **Linux Integrity Measurement Architecture (IMA)** subsystem it has been decided that by now it is preferable to continue using the **security** boot parameter instead of the **lsm** one.
See https://github.com/openSUSE/kernel-source/commit/953db3507d62938038cd5f2d4bbe7fd0cb3d3763
- https://bugzilla.suse.com/show_bug.cgi?id=1194332
**Note**: We could write **lsm=integrity,apparmor** when **apparmor** is selected having the same value we have by default but that looks strange and we should add it in case we allow to select a list of modules to be set during installation.
=> Use security

package/yast2-security.changes, package/yast2-security.spec, src/clients/security_auto.rb
The requirement was not updated since we moved the **SELinux** class under **LSM** (related to #115)
- https://bugzilla.suse.com/show_bug.cgi?id=1194449
Fix the dependency
Tested manually but we probably should add a unit test for the auto client **ASAP**.
=> Fix security auto requirement

package/yast2-security.changes, package/yast2-security.spec, src/autoyast-rnc/security.rnc
It will allow to hide the option in case of not wanted:
```xml
<?xml version="1.0"?>
<!DOCTYPE profile>
<profile xmlns="http://www.suse.com/1.0/yast2ns" xmlns:config="http://www.suse.com/1.0/configns">
<security>
<lsm>
<select>apparmor</select>
<configurable config:type="boolean">true</configurable>
<none>
<selectable config:type="boolean">false</selectable>
</none>
</lsm>
</security>	
</profile>
```
related to #115
=> Autoyast LSM section: Added 'none' subsection allowing to mark the module as not selectable

package/yast2-security.changes, package/yast2-security.spec, src/lib/y2security/lsm/none.rb, test/y2security/lsm/none_test.rb
Even for the _None_ option, which was forgotten when going back from the recommended `lsm` to the `security` one. See https://github.com/yast/yast-security/pull/118.
This should fix https://bugzilla.suse.com/show_bug.cgi?id=1196274
=> Stop using the 'lsm' kernel boot parameter

package/yast2-security.changes, package/yast2-security.spec, src/lib/y2security/lsm/config.rb, test/y2security/lsm/config_test.rb
While locally testing https://github.com/yast/yast-users/pull/366, I realize that test suite was crashing because `Y2Security::LSM::Config#active`, which was performing a call to the `#split` method over a `nil` value. 
Ensure that the result of `Yast::SCR.Read` is always a string.
- Added a new unit test
- Tested manually
=> Do not crash if reading active LSM modules returns nil

src/lib/y2security/clients/security_policy_proposal.rb, src/lib/y2security/security_policies/disa_stig_policy.rb, src/lib/y2security/security_policies/manager.rb, src/lib/y2security/security_policies/policy.rb, test/test_helper.rb, test/y2security/clients/security_policy_proposal_test.rb, test/y2security/security_policies/manager_test.rb
- https://trello.com/c/H2WYkfZf/3081-3-stig-trigger-check-on-first-boot-with-persisted-list-of-disabled-rules
* When a security policy is enabled, set the `ssg-apply` package and service for installation.
* When no security policies are enabled, remove the `ssg-apply` package and service.
=> Enable/disable the ssg-apply service according to the security policies

doc/security_policies.md, src/lib/cfa/ssg_apply.rb, src/lib/y2security/clients/security_policy_proposal.rb, src/lib/y2security/security_policies/disa_stig_policy.rb, src/lib/y2security/security_policies/manager.rb, src/lib/y2security/security_policies/policy.rb, src/lib/y2security/security_policies/unknown_rule.rb, src/modules/Security.rb, test/cfa/ssg_apply_test.rb, test/data/system/etc/ssg-apply/default.conf, test/data/system/etc/ssg-apply/override.conf, test/security_test.rb, test/test_helper.rb, test/y2security/clients/security_policy_proposal_test.rb, test/y2security/security_policies/manager_test.rb, test/y2security/security_policies/unknown_rule_test.rb
The `ssg-apply` tool read its configuration from the `default.conf` and `override.conf` files in the`/etc/ssg-apply` directory. The idea of this PR is to write the configuration in the latter of those files, including the policy to apply and the rules to ignore.
This PR also contains some fixes in the policies proposal.
=> Write `ssg-apply` configuration file

src/lib/y2security/clients/security_policy_proposal.rb, src/lib/y2security/security_policies/bootloader_password_rule.rb, src/lib/y2security/security_policies/disa_stig_policy.rb, src/lib/y2security/security_policies/encrypted_filesystems_rule.rb, src/lib/y2security/security_policies/filesystem_size_rule.rb, src/lib/y2security/security_policies/firewall_enabled_rule.rb, src/lib/y2security/security_policies/manager.rb, src/lib/y2security/security_policies/no_wireless_rule.rb, src/lib/y2security/security_policies/rule.rb, src/lib/y2security/security_policies/separate_filesystem_rule.rb, src/lib/y2security/security_policies/separate_mount_point_rule.rb, src/lib/y2security/security_policies/unknown_rule.rb, src/modules/Security.rb, test/security_test.rb, test/y2security/clients/security_policy_proposal_test.rb, test/y2security/security_policies/bootloader_password_rule_test.rb, test/y2security/security_policies/disa_stig_policy_test.rb, test/y2security/security_policies/encrypted_filesystems_rule_test.rb, test/y2security/security_policies/filesystem_size_rule_test.rb, test/y2security/security_policies/firewall_enabled_rule_test.rb, test/y2security/security_policies/separate_filesystem_rule_test.rb, test/y2security/security_policies/separate_mount_point_rule_test.rb, test/y2security/security_policies/unknown_rule_test.rb
Rule CCE identifier is not show.
https://trello.com/c/wHVROKfC/3126-1-display-both-cce-and-sles-15-identifiers-for-each-stig-rule
Show CCE identifier and SUSE reference in a second line for each rule.
Note: disabling rule is not offered any more.
- Added unit tests
- Tested manually
=> Rules with identifiers and references

src/lib/y2security/clients/security_policy_proposal.rb, src/lib/y2security/security_policies/rule_presenter.rb, test/y2security/security_policies/rule_presenter_test.rb
Failing rules are now presented in two lines, see https://github.com/yast/yast-security/pull/139. And failing rules are also shown in the storage Guide Proposal and Expert Partitioner. We have an internal RulePresenter class, so it would be nice to use it from yast-storage-ng. 
Promote `Y2Security::SecurityPolicies::RulePresenter` as part of the publilc API.
See https://github.com/yast/yast-storage-ng/pull/1308/commits/4f70300a35e081259fa60c7ae038e586caa97f55.
- Added new unit test
- Tested manually
=> Expose RulePresenter class

src/lib/cfa/ssg_apply.rb, src/lib/y2security/clients/security_policy_proposal.rb, src/lib/y2security/security_policies/disa_stig_policy.rb, src/lib/y2security/security_policies/manager.rb, src/lib/y2security/security_policies/policy.rb, test/cfa/ssg_apply_test.rb, test/y2security/clients/security_policy_proposal_test.rb, test/y2security/security_policies/manager_test.rb
This PR adds support for setting the action to be performed using SCAP during the first boot, among other changes.
* Allow setting an action for the first boot (*nothing*, *scan only* or *scan and remediate*).
* Report an error instead of blocking the installation when the security policy is not met.
* Changes in `ssg-apply` configuration:
* Update the `remediate` value (`yes` for `scan and remediate`; `no` for `scan` only).
* Do not write the remediation script and the list of disabled rules to the `ssg-apply` configuration.
* Use `/etc/ssg-apply/default.conf` as base for the configuration file.
* Write the list of failing rules to `/var/log/YaST2/security_policies_failed_rules`.
* Add a help text specifying how the feature works.
<details>
<summary>Summary including the new feature to …
=> Set the action to be performed by SCAP on first boot

src/lib/y2security/security_policies/disa_stig_policy.rb, src/lib/y2security/security_policies/manager.rb, test/security_test.rb, test/y2security/security_policies/manager_test.rb
The profile "disa_stig" does not exists.
Use `stig` instead of `disa_stig` as profile name for ssg-apply configuration.
=> Use "stig" as profile name for DISA STIG

src/autoyast-rnc/security.rnc, src/lib/y2security/autoinst_profile/security_policy_section.rb, src/lib/y2security/autoinst_profile/security_section.rb, src/lib/y2security/security_policies/manager.rb, src/modules/Security.rb, test/security_test.rb, test/y2security/autoinst_profile/security_policy_section_test.rb, test/y2security/autoinst_profile/security_section_test.rb, test/y2security/security_policies/manager_test.rb
This PR adapts the AutoYaST bits of this module to support the new design/API. Bear in mind that only one security policy can be applied to a machine. As a consequence, the <security_policy>` section in an AutoYaST profile should look like this:
```xml
<security>
<security_policy>
<action>remediate</action> 
<policy>stig</policy> 
</security_policy>
<selinux_mode>permissive</selinux_mode>
<lsm_select>selinux</lsm_select>
</security>
```
The counterpart of this PR is https://github.com/yast/yast-autoinstallation/pull/845.
=> AutoYaST: adapt to the new schema of the security_policies section

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb
https://bugzilla.suse.com/show_bug.cgi?id=1205918
https://trello.com/c/Wns8fhe8/
While saving any changes in the YaST Security module, there is a crash (that is not reported to the user!) with this backtrace in the y2log:
```
2022-12-01 02:45:17 <3> susetest(9049) [Ruby]
modules/Progress.rb(UpdateProgressBar):606
Progress bar has only 4 steps, not 5.
------------- Backtrace begin -------------
.../modules/Progress.rb:606:in `UpdateProgressBar'
.../modules/Progress.rb:661:in `NextStep'
.../modules/Progress.rb:671:in `NextStage'
.../modules/Security.rb:764:in `Write'
.../include/security/complex.rb:50:in `WriteDialog'
.../include/security/wizards.rb:133:in `block in SecuritySequence'
.../vendor_ruby/3.1.0/yast/builtins.rb:546:in `eval'
.../modules/Sequencer.rb:247:in `WS_run' …
```
=> Fix for Crash during Saving [SLE-15 SP4]

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb
_**This is the merge to master.** The original fix for SLE-15-SP4 is https://github.com/yast/yast-security/pull/149._
https://bugzilla.suse.com/show_bug.cgi?id=1205918
https://trello.com/c/Wns8fhe8/
While saving any changes in the YaST Security module, there is a crash (that is not reported to the user!) with this backtrace in the y2log:
```
2022-12-01 02:45:17 <3> susetest(9049) [Ruby]
modules/Progress.rb(UpdateProgressBar):606
Progress bar has only 4 steps, not 5.
------------- Backtrace begin -------------
.../modules/Progress.rb:606:in `UpdateProgressBar'
.../modules/Progress.rb:661:in `NextStep'
.../modules/Progress.rb:671:in `NextStage'
.../modules/Security.rb:764:in `Write'
.../include/security/complex.rb:50:in `WriteDialog'
.../include/security/wizards.rb:133:in `block in …
```
=> Fix for Crash during Saving [master]

package/yast2-security.changes, package/yast2-security.spec, src/lib/y2security/autoinst_profile/security_policy_section.rb, src/lib/y2security/security_policies/manager.rb, src/modules/Security.rb, test/security_test.rb, test/y2security/autoinst_profile/security_policy_section_test.rb, test/y2security/security_policies/manager_test.rb
The `security_policy` section is not exported when cloning a system with AutoYaST.
If the `/etc/ssg-apply/override.conf` file exists (written by AutoYaST), infer and export the settings.
* If the `ssg-apply` is disabled, set the `action` to "none".
* If the `ssg-apply` is enabled...
* ... and `remediate` is set to `yes` in the configuration, set the action to `remediate`.
* ... and `remediate` is set to `no` in the configuration, set the action to `scan`.
- Added a new unit test
- Tested manually
=> Export security policy settings

package/yast2-security.changes, package/yast2-security.spec, src/lib/y2security/security_policies/manager.rb, test/y2security/security_policies/manager_test.rb
AutoYaST does not clone the `<security_policy/>` section when the action is set to `none`:
```xml
<security_policy>
<action>none</action>
<profile>stig</profile>
</security_policy>
```
In that case, YaST does not write an `/etc/ssg-apply/override.conf` file, so there is no way to infer that security policy checks were enabled at installation time. Checking whether `ssg-apply` package is installed does not look like a valid way to determine it because you might get a `<security_policy/>` section just for installing the package.
Starting in `yast2-security 4.4.19`, if a security policy is enabled at installation time, YaST *always* writes the `override.conf` file. So when cloning the system, it exports a `<security_policy/>` section if that file exists.
This solution is good enough, but we …
=> Always write override conf

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb, test/security_test.rb
*Short description of the original problem.*
- [bsc#1208492](https://bugzilla.suse.com/show_bug.cgi?id=1208492)
It seems to be consequence of moving from ```/etc/login.defs``` to ```/etc/login.defs.d/70-yast.defs```.
Login.defs attributes cannot contain empty values (by definition).  The module contains a list of supported attributes which are handled in a way (one of them is e.g. USERADD_CMD which can be seen in the bug report above). ```/etc/login.defs``` used to contain all those attributes with some value, so the module internals were filled with some values. Since that changed and source file(s) needn't to exist, the internals are not correctly filled and an empty value could be used later when writing configuration.
When preparing attributes for writing, filter out those with empty …
=> Do not push empty value into login.defs model

package/yast2-security.changes, package/yast2-security.spec, src/lib/y2security/security_policies/target_config.rb
The initialization of the TargetConfig creates an instance of the security_settings which reads the defaults for ssh, firewall and vnc from the skelcd even when it does not need this configuration at all causing problems when it is read to early during the workflow or when it is not needed as commented.
In the related bug, it adds the package firewalld because according to the skelcd it needs to be enabled even if in the profile it is disabled or removed.
- https://bugzilla.suse.com/show_bug.cgi?id=1216615
Do a lazy initialization of the settings just when required.
- *Tested manually*
=> Do a lazy initialization of network and security settings

package/yast2-security.changes, package/yast2-security.spec, src/autoyast-rnc/security.rnc, src/data/security/level1.yml, src/data/security/level2.yml, src/data/security/level3.yml, src/modules/Security.rb, test/data/system/etc/login.defs, test/security_test.rb
https://bugzilla.suse.com/show_bug.cgi?id=1231006
https://trello.com/c/YaAqN3hc/
**This is for master / Factory only.** SLE-15-SPx / Leap 15.x still support those scripts.
On Factory / Tumbleweed / Slowroll, after using the YaST security module, the `useradd` / `usermod`, / `userdel` commands complain about invalid configuration parameters:
```
sudo usermod -aG docker poltpolt
configuration error - unknown item 'USERADD_CMD' (notify administrator)
configuration error - unknown item 'USERDEL_PRECMD' (notify administrator)
configuration error - unknown item 'USERDEL_POSTCMD' (notify administrator)
```
It turned out that these parameters came from `/etc/login.defs.d/70-yast.defs`, written by the YaST security module:
```
USERADD_CMD /usr/sbin/useradd.local
USERDEL_PRECMD …
```
=> Drop Obsolete login.defs Scripts USERADD_CMD, USERDEL_PRECMD, USERDEL_POSTCMD, GROUPADD_CMD
