package/yast2-security.changes, package/yast2-security.spec, src/clients/security.rb, src/data/security/level1.yml, src/data/security/level2.yml, src/include/security/helps.rb, src/include/security/levels.rb, test/levels_test.rb
Is it necessary to create some kind of compatibility layer for the command line (mapping both "home" and "network" to "workstation")?
=> New security levels

src/include/security/helps.rb, src/include/security/widgets.rb, src/modules/Security.rb, test/security_test.rb
I will add two approach,
this one
and other moving stuf to a specific class: https://github.com/yast/yast-security/pull/33
=> WIP: First aproach without Overengineering S390 hide booting

package/yast2-security.changes, package/yast2-security.spec
- Depend on yast/yast-yast2#450
=> Changed dependency from yast2-mail to yast2 (FATE#319711)

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb, test/security_test.rb
Part of https://trello.com/c/0tG0L56x/161-reorganize-yast2-service-classes
=> Update calls to yast2 systemd services

.travis.yml, package/yast2-security.changes, package/yast2-security.spec, src/include/security/routines.rb, src/modules/Security.rb, test/levels_test.rb, test/security_test.rb
See https://github.com/yast/yast-yast2/pull/988.
=> Read login.defs settings from /usr/etc

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb
trello: https://trello.com/c/Cx9X2roJ/1472-3-get-rid-of-etc-initd-and-sbin-rc-calls
Note: code looks a bit strange and obsolete, but I do not want to touch more then needed.
=> Remove initd

package/yast2-security.changes, package/yast2-security.spec, src/data/security/level1.yml, src/data/security/level2.yml, src/data/security/level3.yml, src/include/security/dialogs.rb, src/modules/Security.rb, test/security_test.rb
Handling Sysctl entries in following files/directories:
/run/sysctl.d,
/etc/sysctl.d
/usr/local/lib/sysctl.d
/usr/lib/sysctl.d
/lib/sysctl.d
/etc/sysctl.conf
=> Using SysctlConfig class

.rubocop.yml, Dockerfile, Rakefile, package/yast2-security.changes
Merge of https://github.com/yast/yast-security/pull/75
(bsc#1177720)
=> Translate <enable_sysrq> to <kernel.sysrq> with the correct value

package/yast2-security.changes, package/yast2-security.spec, src/lib/cfa/selinux.rb, src/lib/y2security/selinux.rb, test/cfa/selinux_test.rb, test/y2security/selinux_test.rb
Addresses problems found in https://github.com/yast/yast-security/pull/87#discussion_r574756489 and https://github.com/yast/yast-security/pull/87#discussion_r574760539
=> Y2Security::Selinux fixes

package/yast2-security.changes, package/yast2-security.spec, src/modules/Security.rb, test/security_test.rb
See https://github.com/yast/yast-security/pull/111.
=> Port PR#111 to master

package/yast2-security.changes
Fix changelog typos introduced here https://github.com/yast/yast-security/pull/111.
=> Fix changelog

package/yast2-security.changes
See https://github.com/yast/yast-security/pull/113.
=> Port PR#113 to master

package/yast2-security.changes, package/yast2-security.spec, src/lib/security/ctrl_alt_del_config.rb, test/security_test.rb
Adapt to `Package` and `PackageSystem` changes. See https://github.com/yast/yast-yast2/pull/1219 for further information.
=> Use `Package` instead of `PackageSystem`

package/yast2-security.changes, package/yast2-security.spec, test/security_test.rb
Fix for failing build / submit request (see https://github.com/yast/yast-security/pull/123#issuecomment-1025612962)
=> Fix export test

package/yast2-security.changes, package/yast2-security.spec, src/lib/security/ctrl_alt_del_config.rb
Use https://github.com/yast/yast-yast2/pull/1249 to avoid potential problems like the one described in [bsc#1196963](https://bugzilla.suse.com/show_bug.cgi?id=1196963).
=> Force package backend

test/security_test.rb
=> Fix security test

doc/security_policies.md
Update security policies doc to reflect the latest API changes.
=> Update security policies doc

src/lib/y2security/clients/security_policy_proposal.rb, test/y2security/clients/security_policy_proposal_test.rb
Block the installation when a security policy check fails.
=> Block installation if security policy checks fail

package/yast2-security.changes, package/yast2-security.spec, src/lib/y2security/autoinst_profile/security_policy_section.rb, src/lib/y2security/security_policies/manager.rb, src/modules/Security.rb, test/security_test.rb, test/y2security/autoinst_profile/security_policy_section_test.rb, test/y2security/security_policies/manager_test.rb
Bring #151 and #152 to `master`.
=> Merge SLE-15-SP4

package/yast2-security.changes, package/yast2-security.spec, src/lib/y2security/security_policies/target_config.rb
Bring #156 fix to the `master` branch.
=> Merge `SLE-15-SP6` into `master`
